app:
  tomcat-base: http://localhost:8081
logging:
  level:
    ROOT: INFO
management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
server:
  servlet:
    context-path: /webapp2
  error:
    include-exception: true
  whitelabel:
    enabled: true
spring:
  application:
    name: Web App Two
  boot:
    admin:
      client:
        instance:
          service-url: ${app.tomcat-base}${server.servlet.context-path}
